version: "3.9"

services:
  redis:
    image: bitnami/redis:7.4.0
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  mongodb:
    image: mongo:7.0.14
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}


  users_service:
    build:
      context: ./user_service
    restart: always
#    ports:
#      - "8081:8080"
    env_file:
      - .env
    network_mode: host


  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    tty: true


  nginx:
    build:
      context: ./other_services/nginx
    ports:
      - "8080:80"
    depends_on:
      - users_service

#
#volumes:
#  db-data:
#  front: