version: "3.9"

services:
  postgres:
    build:
      context: ./services/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}

      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}

  nginx:
    build:
      context: ./services/nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend:/site


