version: "3.9"

services:
  api:
    build:
      context: ./app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    build:
      context: ./services/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}

      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    build:
      context: ./services/nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend:/site

volumes:
  db-data: