version: "3.9"

services:
  users_service:
    build:
      context: ./user_service

    ports:
      - "8043:8080"
    env_file:
      - .env

  telegram_service:
    build:
      context: ./docker/telegram_service
    ports:
      - "8052:8000"

    env_file:
      - .env

  background_tasks:
    build:
      context: ./docker/background_tasks
    env_file:
      - .env

  #  telegram_service:
  #    build:
  #      context: ./telegram_service
  #    restart: unless-stopped
  #    ports:
  #      - "8052:8080"
  #    env_file:
  #      - .env

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    tty: true
