#!/bin/sh

psql -v ON_ERROR_STOP=1 <<-EOSQL
	CREATE USER "$DB_USER";
	ALTER USER "$DB_USER" WITH PASSWORD '$DB_USER_PASSWORD';
	CREATE DATABASE "$DB_NAME" OWNER $DB_USER;
	GRANT ALL PRIVILEGES ON DATABASE "$DB_NAME" TO "$DB_USER";
EOSQL